### ISSUE TITLE
Reading data objects

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledge-south-iec61850#17]
### Abstract

Read simple or complex data attributes/objects with the IedConnection_readObject

**Comment by mbourhis** [comment]
### Requirements : Supported features
['DataModel' is the DataModel of the server, known by the server]
* MMS for reading DA value (defined in the DataModel), with the specified FC
* MMS for reading DO value (set of DA values) (defined in the DataModel), with the specified FC

**Comment by mbourhis** [comment]
### Remarks
* a MMS is only a value (numeric, litteral, boolean,...)
* a MMS structure does not contain the name of the value

**Comment by mbourhis** [comment]
### Remarks: for knowing the 'name' of the values
2 possibilities:
* the client already knows the name of the value it wants to read (MMS, DataSet)
* the client asks the server (for RCB usecase) and memorizes the 'name tree', before the reception of the values

**Comment by mbourhis** [comment]
"complex" means "structured", a data tree.
But we don't known, a priori, the name of each terminal node of the data tree.

**Comment by mbourhis** [comment]
### How to know the name of the read 'values'

The type of the data to read implies some specific parameters:

 * for telesignal 'TS', CDC will be SPS or DPS ("status point"), and FC will be ST
   The values composing the Reading will be: 'stVal' (boolean), 'q' (for quality), 't' (for timestamp).

 *  for telemeasure 'TM', CDC will be MV ("measurement value"), and FC will be MX
    The values composing the Reading will be: 'mag' (float), 'q' (for quality), 't' (for timestamp).
