### ISSUE TITLE
Receiving reports

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledge-south-iec61850#20]
### Abstract 

Reports are used for event based message transmission. If you need to be updated with the states of certain variables reporting provides the means without forcing you to periodically send read requests to the server. This preserves network bandwidth especially in cases where values only change sporadically.

Reports are defined for data sets. A server typically contains preconfigured Report Control Blocks(RCB). A client has to reserve, configure and activate such a RCB prior to receiving report messages from the server.

To handle reports client side these data types are involved:

ClientReportControlBlock – is the data container to hold the RCB values client side
ClientReport – represents a received report
ClientDataSet – container for the data values of a received report
ReportCallbackFunction – callback function when a report is received
ReasonForInclusion – enumeration to indicate the reason for the inclusion of a data set member into the report

**Comment by mbourhis** [comment]
### Requirements : Supported features
['DataModel' is the DataModel of the server, known by the server]
* RCB (Report Control Block) : subscription to a report of 'set of MMS', defined in the DataModel

**Comment by mbourhis** [comment]
### Remarks
* a MMS is only a value (numeric, litteral, boolean,...)
* a MMS structure does not contain the name of the value

**Comment by mbourhis** [comment]
### Remarks: for knowing the 'name' of the values
* the client asks the server (for RCB usecase) and memorizes the 'name tree', before the reception of the values
