### ISSUE TITLE
Monitoring messages acquisition

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledge-south-iec61850#3]

**Comment by mbourhis** [comment]
### Requirements : Supported features
['DataModel' is the DataModel of the server, known by the server]
* MMS for reading DA value (defined in the DataModel), with the specified FC
* MMS for reading DO value (set of DA values) (defined in the DataModel), with the specified FC
* DataSet of MMS: set of MMS (in 1 read operation) (the DataSet is build by the client, not defined in the DataModel)
* RCB (Report Control Block) : subscription to a report of 'set of MMS', defined in the DataModel
* GI: parameter for the sending/reception of one RCB

**Comment by mbourhis** [comment]
### Remarks
* a MMS is only a value (numeric, litteral, boolean,...)
* a MMS structure does not contain the name of the value

**Comment by mbourhis** [comment]
### Remarks: for knowing the 'name' of the values
2 possibilities:
* the client already knows the name of the value it wants to read (MMS, DataSet)
* the client asks the server (for RCB usecase) and memorizes the 'name tree', before the reception of the values
