### ISSUE TITLE
Allow `status-only` type `xxC` common data classes

### ISSUE THREAD

**Issue by JakobVogelsang** [fledge-power/fledge-south-iec61850#33]
**Describe the bug**
IEC 61850 south client fails with error when exchange data is pointing to `DPC` type object (e.g. XCBR1.Pos) with missing data attributes of functional constraint `[CO]`. This is not very uncommon and should in my point of view not be a source for error.

**To Reproduce**
1. Load file with `status-only` `DPC` (e.g. XCBR1.Pos)
2. Make sure that this specific is requested in `exchange_data`
3. See error log and sniffer results. I see there a `GetDataDefinition` pointing to this very object requesting definition for data attributes of the type `[CO]`

**Expected behavior**
Allow `xxC` type common data classes of type `status-only`

**Comment by mzillgith** [comment]
Can you upload the error log and sniffer output? Didn't it work to read the status value or is the problem just the warning in the log?

**Comment by JakobVogelsang** [comment]
No the client does expect data structures with the function constraint `[CO]` to be present. This might not be the case when the `ctlModel` is status only. I will upload the SCL file including the pcap files for further discussion.

**Comment by jude-adam** [comment]
The plugin works with Status-only, however it shows a warning message for not being able to create a Control Object Client when there is no CO. This has been fixed and will be pushed soon (no warning log will be shown for objects with Status-Only ctlModel) .

**Comment by aklira** [comment]
Can we close this issue if the answer is OK ?

**Comment by JakobVogelsang** [comment]
There is a workaround: Define as `DpsTyp`. Still, I think that is misleading. IEC61850 defines DPC which allows both read status data and control. More than that, there are cases where DPC type CDCs are used for monitoring purpose only. This seems not to be the case in the pivot model. It is misleading and should have proper documentation.

**Comment by jude-adam** [comment]
> There is a workaround: Define as `DpsTyp`. Still, I think that is misleading. IEC61850 defines DPC which allows both read status data and control. More than that, there are cases where DPC type CDCs are used for monitoring purpose only. This seems not to be the case in the pivot model. It is misleading and should have proper documentation.

I don't believe this is necessary, I tested in the newest version and DPC works fine in both ways (status and control). Using the SCD file and config given in issue #37 , a DpcTyp's status values are sent as readings.

**Comment by JakobVogelsang** [comment]
I can confirm it is working. There is just a small thing that you only can see on the sniffer:

I see a service asking for the `ctlModel` like so:
- GetDataValue of ....Pos.ctlModel answered with integer 0

After that there is a GetDataDefinition for
- GetDataDefinition ....Pos[CO]

Why the second request if you already know the ctlModel is status-only.
