### ISSUE TITLE
Misleading information on the wiki page for `report_subscriptions`

### ISSUE THREAD

**Issue by JakobVogelsang** [fledge-power/fledge-south-iec61850#35]
According to the wiki the key `dataset_ref` is optional. This does make sense as static reports are configured with a datSet reference. When I leave this key out in start the client I see in the sniffer this content:

<img width="1653" alt="grafik" src="https://github.com/fledge-power/fledge-south-iec61850/assets/66802940/12c859ed-e680-4650-ba59-ddafcf4828e6">

**Config:**
```ts
{
 "protocol_stack": {
  "name": "iec61850client",
  "version": "0.0.1",
  "transport_layer": {
   "ied_name": "IED1",
   "connections": [
    {
     "ip_addr": "192.168.0.67",
     "port": 49152,
     "tls": false
    }
   ]
  },
  "application_layer": {
   "polling_interval": 5000,
   "datasets": [
    {
     "dataset_ref": "IEDLDevice/LLN0.SwitchGear",
     "entries": [
      "IEDLDevice/XCBR1.Pos.stVal[ST]",
      "IEDLDevice/XCBR1.Pos.q[ST]"
     ]
    }
   ],
   "report_subscriptions": [
    {
     "rcb_ref": "IEDLDevice/LLN0.RP.SwitchGear01"
    }
   ]
  }
 }
}
```

**PCAP:**
[MissingDataSetPath.pcap.zip](https://github.com/fledge-power/fledge-south-iec61850/files/14238774/MissingDataSetPath.pcap.zip)

**Comment by mzillgith** [comment]
Thank you for the hint. I fixed the wiki so it's clear that it's mandatory. We will also add an error log message and not sending the request with the empty name.

**Comment by JakobVogelsang** [comment]
Fixed thank you
