### ISSUE TITLE
Protocol stack configuration management

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledge-south-iec61850#5]
Abstract
The objective is to configure the transport, application and security layer of the protocol stack of the IEC 61850 client (south plugin) which ensures communication with the IED server in order to provide the communication service.
A data model in JSON format must be defined, ingested via the Fledge API, checked for data validity and mapped with the configuration functions of the protocol library.
Pre-requisites
[Read the design document](https://wiki.lfenergy.org/display/FLED/Plugins+configuration+design)
Test data
Rules : rules, errors and logs
R1: check if the JSON is a valid document.
Acceptance criteria
Given a JSON configuration file
When: the configuration file is received
Then: the south plugin starts and uses the configuration defined in the JSON file.

**Comment by mbourhis** [comment]
Specifications for the JSON document: https://wiki.lfenergy.org/display/FLED/IEC+61850+south+plugin

**Comment by mbourhis** [comment]
The TLS support will be added in another ticket: https://github.com/fledge-power/fledge-south-iec61850/issues/11

Libiec61850 has TLS support, by using mbedtls.

The parameters for the 'security layer' are the same as the TLS parameters found in 'fledge-south-iec104'.

**Comment by mbourhis** [comment]
The OSI parameters are now supported:
see the git branch: https://github.com/fledge-power/fledge-south-iec61850/tree/mbourhis/add-OSI-connection-parameters

**Comment by mbourhis** [comment]
### Application layer

the list of parameters has to be defined. Here, some suggestions:

* period of time, between 2 connection attempts, when connection is down
* --boolean about the activation of the 'debug' MMS reading by polling--
* frequency of the MMS reading by polling

**Comment by mbourhis** [comment]
### Application layer

* read_polling_period_in_ms (0 will disable loop reading, only one read)
