### ISSUE TITLE
Exchanged messages configuration management

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledge-south-iec61850#6]
Abstract
In order to configure the messages exchanged by the IEC 61850 client (south plugin) with the IED server, a data model in JSON format must be defined, ingested via the Fledge API and the validity of the data checked.
Pre-requisites
[Read the design document](https://wiki.lfenergy.org/display/FLED/Plugins+configuration+design)
Test data
Rules : rules, errors and logs
R1: check if the JSON is a valid document.
Acceptance criteria
Given a JSON configuration file
When: the configuration file is received
Then: the south plugin starts and uses the configuration defined in the JSON file.

**Comment by mbourhis** [comment]
### Proposition of ExchangedData JSON for an export of IEC61850 DO (Data object):

```
   "exchanged_data":{
      "name":"SAMPLE",
      "version":"1.0",
      "datapoints":[
         {
            "label":"TS1",
            "pivot_id":"ID114562",
            "pivot_type":"SpsTyp",
            "pivot_subtypes":[
               "transient"
            ],

            "protocols":[
               {
                  "name":"iec61850",
                  "address":"simpleIOGenericIO/GGIO1.SPCSO1",
                  "typeid":"SP"
               }
            ]
         },
         {
            "label":"TM1",
            "pivot_id":"ID99876",
            "pivot_type":"MVTyp",
            "tfid":"square_root",
            "params":[
               2.0,
               49.5
            ],

            "deadband":[
               -0.02,
               0.02
            ],

            "protocols":[
               {
                  "name":"iec61850",
                  "address":"simpleIOGenericIO/GGIO1.AnIn1",
                  "typeid":"MV"
               }
            ]
         }
      ]
   }
```
