### ISSUE TITLE
Clock synchronisation

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledge-south-iec61850#7]

**Comment by mbourhis** [comment]
### some investigations
* libiec61850 can read timestamp, and generated timestamp
* libiec61850 handles the 'Timestamp' object that indicates the status of the clock synchronization ('yes', 'no', 'based on external clock signal', 'failure', ...)
* in libiec61850 there is no message to make or trigger a clock synchronization
* in libiec61850, the feature 'synchrocheck' is supported, for the control commands (but it is not a clock synchronization, it is a synchronization for triggering the command based on a voltage input)
* The IEC61850 standard indicates that the Clock synchronization is based on PTP with constant parameters ( https://en.wikipedia.org/wiki/IEC/IEEE_61850-9-3#IEEE_1588_settings) and some additional parameters (https://en.wikipedia.org/wiki/IEC/IEEE_61850-9-3#Additions_to_IEEE_Std_1588)
* PTP protocol and synchronization is supported by the Linux kernel, with a specific driver (https://www.kernel.org/doc/html/latest/driver-api/ptp.html). This driver could be install on the platforms (package available for Debian family, for instance)
> Description-en: Precision Time Protocol (PTP, IEEE1588) implementation for Linux
> Linuxptp is an implementation of the Precision Time Protocol (PTP)
> according to IEEE standard 1588 for Linux. Features include:
>  - support for hardware and software time stamping via the Linux
>    SO_TIMESTAMPING socket option.
>  - support for the Linux PTP Hardware Clock (PHC) subsystem by using the
>    clock_gettime family of calls, including the new clock_adjtimex
>    system call
>  - implementation of Boundary Clock (BC) and Ordinary Clock (OC)
>  - transport over UDP/IPv4, UDP/IPv6, and raw Ethernet (Layer 2)
>  - support for IEEE 802.1AS-2011 in the role of end station
> .
> PTP provides higher precision and faster synchronization than NTP even
> without hardware support. With hardware support, sub-microsecond
> accuracy can be expected. Whereas NTP is intended for WAN use, PTP is
> designed for LAN environments and makes use of UDP multicast.

**Comment by mbourhis** [comment]
The IEC61850 standard requires some time precision and time accuracy, but
these features are managed by PTP, and not directly by IEC61850 itself:

https://www.youtube.com/watch?v=gYAdIQQkB5M
https://www.youtube.com/watch?v=70DQ8Ipk9Xg
